### PR TITLE
feat: add stripe checkout

### PR DESCRIPTION
**Pull request by notrab**
This is a WIP PR that adds the checkout flow.

Test card during checkout `4242 4242 4242 4242`.

### CODE REVIEW

**Comment by domtaylor** [comment]
Any plans to fix the 'window not defined' Webpack deploy issue. I have tried both recommended methods of adding if (typeof window !== 'undefined') to Provider.js where it is failing and also fallback of componentDidMount() in gatsby-ssr  but now I get: WebpackError: Please pass a valid Stripe object to StripeProvider. You can obtain a Stripe object by calling 'Stripe(...)' with your publishable key. I switched apiKey to stripe in StripeProvider component and have also set my key in .env. Deploy still fails.

**Comment by notrab** [comment]
Hi @domtaylor 

We're working on some updates to the demo store which will include further fixes/features.

Expect these to land in July. If you have any suggestions or fixes, please feel free to PR 😄

**Comment by domtaylor** [comment]
thanks @notrab I am working on a solution I will PR when done. Looking forward to the updates in July, it's a great demo store.

**Comment by ynnoj** [comment]
@domtaylor Can't wait to see it! 🚀

**Comment by domtaylor** [comment]
@notrab @ynnoj actually can be solved quite easily by not providing StripeProvider in Gatsby SSR. But here's the updated code I used to get it passing. Props also to @DerekNguyen for helping. 

import React, { useState, useEffect } from 'react'
import { ShopkitProvider } from './src/shopkit'
import { StripeProvider, Elements } from 'react-stripe-elements'
import Layout from './src/components/Layout' 

const StripeWrapper = ({ children }) => {
  const [ stripe, setStripe ] = useState(null)

  useEffect(() => {
    // for SSR
    if (typeof window == 'undefined') return

    // for browser
    if (window.Stripe) {
      setStripe(window.Stripe(process.env.GATSBY_STRIPE_PUBLISHABLE_KEY))
    } else {
      const stripeScript = document.querySelector('#stripe-js')
      stripeScript.onload = () => {
        setStripe(window.Stripe(process.env.GATSBY_STRIPE_PUBLISHABLE_KEY))
      }
    }
  }, []) // <-- passing in an empty array since I only want to run this hook once

  return (
    <StripeProvider stripe={stripe}>
      {children}
    </StripeProvider>
  )
}

export const wrapRootElement = ({ element }) => (
  <StripeWrapper>
       <ShopkitProvider clientId={process.env.GATSBY_MOLTIN_CLIENT_ID}>
            <Elements>{element}</Elements> 
          </ShopkitProvider>
  </StripeWrapper>
)
/* /* export const wrapRootElement = ({ element }) => {
      return (
          <StripeProvider>
          <ShopkitProvider clientId={process.env.GATSBY_MOLTIN_CLIENT_ID}>
            <Elements>{element}</Elements> 
          </ShopkitProvider>
          </StripeProvider>
  )
} */
export const wrapPageElement = ({ element, props }) => {
  return <Layout {...props}>{element}</Layout>
}

**Pull request closed without merging**
